#!/usr/bin/expect -f

spawn java -jar Mars4_5.jar nc forReal.asm
expect "triangleNum width height = "
send "1\r100\r100\r"
expect "h x0 y0 x1 y1 x2 y2 = "
send "1\r"
send "40\r90\r"
send "10\r50\r"
send "50\r5\r"
expect "r g b = "
send "100\r0\r0\r"
expect "exit OK"
close


spawn -ignore HUP feh out.bmp --force-aliasing --auto-zoom
exit
