#!/usr/bin/expect -f

spawn java -jar Mars4_5.jar nc forReal.asm
expect "triangleNum width height = "
send "2\r100\r100\r"
expect "h x0 y0 x1 y1 x2 y2 = "
send "1\r"
send "10\r90\r"
send "90\r50\r"
send "80\r5\r"
expect "r g b = "
send "100\r0\r0\r"
expect "h x0 y0 x1 y1 x2 y2 = "
send "2\r"
send "90\r90\r"
send "20\r30\r"
send "80\r50\r"
expect "r g b = "
send "0\r100\r0\r"
expect "exit OK"
close


spawn -ignore HUP feh out.bmp --force-aliasing --auto-zoom
exit
