#!/usr/bin/expect -f

spawn java -jar Mars4_5.jar nc forReal.asm
expect "triangleNum width height = "
send "4\r250\r250\r"

expect "h x0 y0 x1 y1 x2 y2 = "
send "8\r"
send "125\r225\r"
send "10\r125\r"
send "200\r225\r"
expect "r g b = "
send "100\r0\r0\r"

expect "h x0 y0 x1 y1 x2 y2 = "
send "3\r"
send "200\r200\r"
send "175\r175\r"
send "175\r10\r"
expect "r g b = "
send "0\r0\r100\r"

expect "h x0 y0 x1 y1 x2 y2 = "
send "2\r"
send "50\r100\r"
send "175\r80\r"
send "100\r10\r"
expect "r g b = "
send "100\r100\r0\r"

expect "h x0 y0 x1 y1 x2 y2 = "
send "1\r"
send "10\r225\r"
send "150\r200\r"
send "20\r50\r"
expect "r g b = "
send "0\r100\r100\r"

expect "exit OK"
close


spawn -ignore HUP feh out.bmp --force-aliasing --auto-zoom
exit
